/**
 * polygon-clean.js — Robust offset-polygon cleanup via self-intersection
 * detection and outermost-contour extraction.
 *
 * When a closed polygon is generated by offsetting a centerline (e.g. for
 * track boundaries), tight curves cause the offset curve to self-intersect,
 * producing interior loops that must be removed.  The classical approach is:
 *
 *   1. Detect all edge-edge self-intersections in the offset polygon.
 *   2. Split every crossing edge at the intersection point, producing a
 *      planar subdivision with no crossings.
 *   3. Walk the subdivision choosing the leftmost (outermost) turn at every
 *      junction to extract the single simple contour that encloses the
 *      maximum area — this is the clean boundary.
 *
 * Complexity: O(n²) intersection scan is perfectly fine for the vertex
 * counts we deal with (≤ 500).  No external dependencies.
 */

// ─── Geometry primitives ────────────────────────────────────────────────

/** Signed area of a closed polygon (positive = CCW). */
export function signedLoopArea(loop) {
  let sum = 0;
  for (let i = 0, n = loop.length; i < n; i++) {
    const a = loop[i];
    const b = loop[(i + 1) % n];
    sum += a.x * b.y - b.x * a.y;
  }
  return sum * 0.5;
}

/**
 * Intersect two infinite lines given as (point, direction).
 * Returns the intersection point or null if parallel.
 */
export function intersectLines(aPoint, aDir, bPoint, bDir) {
  const det = aDir.x * bDir.y - aDir.y * bDir.x;
  if (Math.abs(det) < 1e-10) return null;
  const dx = bPoint.x - aPoint.x;
  const dy = bPoint.y - aPoint.y;
  const t = (dx * bDir.y - dy * bDir.x) / det;
  return {
    x: aPoint.x + aDir.x * t,
    y: aPoint.y + aDir.y * t,
  };
}

// ─── Segment-segment intersection ───────────────────────────────────────

const SEG_EPS = 1e-9;

/**
 * Test whether two closed segments [a1,a2] and [b1,b2] intersect.
 * Returns { t, u, x, y } where t ∈ [0,1] is the parameter on edge A and
 * u ∈ [0,1] on edge B, or null if they don't cross.
 *
 * We deliberately exclude near-endpoint hits (t or u very close to 0 or 1)
 * because those arise from shared vertices in a polygon and are not true
 * self-intersections.
 */
function segSegIntersection(a1, a2, b1, b2, endpointMargin = 1e-4) {
  const dax = a2.x - a1.x;
  const day = a2.y - a1.y;
  const dbx = b2.x - b1.x;
  const dby = b2.y - b1.y;
  const denom = dax * dby - day * dbx;
  if (Math.abs(denom) < SEG_EPS) return null; // parallel / collinear

  const oax = b1.x - a1.x;
  const oay = b1.y - a1.y;
  const t = (oax * dby - oay * dbx) / denom;
  const u = (oax * day - oay * dax) / denom;

  if (
    t < endpointMargin || t > 1 - endpointMargin ||
    u < endpointMargin || u > 1 - endpointMargin
  ) {
    return null;
  }

  return {
    t,
    u,
    x: a1.x + dax * t,
    y: a1.y + day * t,
  };
}

// ─── Step 1: find all self-intersections ────────────────────────────────

/**
 * Brute-force O(n²) scan of all non-adjacent edge pairs in a closed loop.
 * Returns an array of { edgeA, edgeB, t, u, x, y }.
 */
function findSelfIntersections(loop) {
  const n = loop.length;
  const hits = [];
  for (let i = 0; i < n; i++) {
    const a1 = loop[i];
    const a2 = loop[(i + 1) % n];
    // Only test edges that don't share a vertex (skip i+1, i-1).
    for (let j = i + 2; j < n; j++) {
      if (j === (i - 1 + n) % n) continue; // wrapping adjacency
      if (i === 0 && j === n - 1) continue; // first-last adjacency
      const b1 = loop[j];
      const b2 = loop[(j + 1) % n];
      const hit = segSegIntersection(a1, a2, b1, b2);
      if (hit) {
        hits.push({edgeA: i, edgeB: j, ...hit});
      }
    }
  }
  return hits;
}

// ─── Step 2: split edges at intersection points ─────────────────────────

/**
 * Insert intersection points into the polygon's edge list, producing a
 * new vertex array where no edges cross.  Each original vertex gets an
 * `origIdx` tag so we can trace provenance if needed.
 *
 * For each edge that has one or more intersection points, we sort them
 * by parameter t and splice them in.
 */
function splitEdgesAtIntersections(loop, intersections) {
  const n = loop.length;

  // Group intersection points by the edge they lie on.
  // Each intersection produces a split on both edgeA and edgeB.
  const edgeSplits = new Array(n);
  for (let i = 0; i < n; i++) edgeSplits[i] = [];

  let xid = 0;
  for (const hit of intersections) {
    const id = xid++;
    edgeSplits[hit.edgeA].push({param: hit.t, x: hit.x, y: hit.y, id});
    edgeSplits[hit.edgeB].push({param: hit.u, x: hit.x, y: hit.y, id});
  }

  // Sort each edge's splits by parameter and build the output array.
  const result = [];
  for (let i = 0; i < n; i++) {
    result.push({x: loop[i].x, y: loop[i].y, origIdx: i, xid: -1});
    const splits = edgeSplits[i];
    if (splits.length) {
      splits.sort((a, b) => a.param - b.param);
      for (const sp of splits) {
        result.push({x: sp.x, y: sp.y, origIdx: -1, xid: sp.id});
      }
    }
  }

  return result;
}

// ─── Step 3: extract outermost contour ──────────────────────────────────

/**
 * Build the planar graph from the split polygon and extract one face
 * using a consistent turn-direction walk from a hull vertex.
 *
 * @param {Array} splitLoop  - vertices after edge splitting
 * @param {number} turnSign  - +1 for leftmost (CCW outer), -1 for rightmost (CW outer)
 * @returns {Array<{x:number, y:number}>}
 */
function walkContour(splitLoop, turnSign) {
  const n = splitLoop.length;
  if (n < 3) return splitLoop.map((p) => ({x: p.x, y: p.y}));

  // ── Build graph ────────────────────────────────────────────────────
  // Merge coincident intersection vertices into single graph nodes.
  const MERGE_EPS = 1e-6;
  const nodeMap = new Map();
  const nodes = []; // [{x, y, adj: [{to, dx, dy}]}]

  function nodeKey(x, y) {
    const qx = Math.round(x / MERGE_EPS) * MERGE_EPS;
    const qy = Math.round(y / MERGE_EPS) * MERGE_EPS;
    return `${qx.toFixed(8)},${qy.toFixed(8)}`;
  }

  const vertexNode = new Array(n);
  for (let i = 0; i < n; i++) {
    const key = nodeKey(splitLoop[i].x, splitLoop[i].y);
    if (nodeMap.has(key)) {
      vertexNode[i] = nodeMap.get(key);
    } else {
      const idx = nodes.length;
      nodes.push({x: splitLoop[i].x, y: splitLoop[i].y, adj: []});
      nodeMap.set(key, idx);
      vertexNode[i] = idx;
    }
  }

  // Add directed edges in polygon order.
  const edgeUsed = new Map();
  for (let i = 0; i < n; i++) {
    const from = vertexNode[i];
    const to = vertexNode[(i + 1) % n];
    if (from === to) continue;
    const dx = nodes[to].x - nodes[from].x;
    const dy = nodes[to].y - nodes[from].y;
    nodes[from].adj.push({to, dx, dy});
    edgeUsed.set(`${from},${to}`, 0);
  }

  // ── Find start vertex on convex hull ───────────────────────────────
  // Topmost (min y), then leftmost — guaranteed on outer boundary.
  let startNode = 0;
  for (let i = 1; i < nodes.length; i++) {
    if (
      nodes[i].y < nodes[startNode].y ||
      (nodes[i].y === nodes[startNode].y && nodes[i].x < nodes[startNode].x)
    ) {
      startNode = i;
    }
  }

  // ── Walk with consistent turn preference ───────────────────────────
  // We pretend we arrived heading left (dx=-1, dy=0).  The reference
  // direction is the reverse of the incoming = (1, 0).
  //
  // For CCW winding (positive area, turnSign=+1):
  //   Pick the edge with the LARGEST signed angle from ref → most CCW.
  // For CW winding (negative area, turnSign=-1):
  //   Pick the edge with the SMALLEST signed angle → most CW.
  let inDx = -1;
  let inDy = 0;
  let current = startNode;
  const contour = [];
  const MAX_STEPS = n * 2 + 10;

  for (let step = 0; step < MAX_STEPS; step++) {
    contour.push({x: nodes[current].x, y: nodes[current].y});

    const adj = nodes[current].adj;
    if (!adj.length) break;

    const refDx = -inDx;
    const refDy = -inDy;

    let bestIdx = -1;
    let bestScore = -Infinity;

    for (let k = 0; k < adj.length; k++) {
      const e = adj[k];
      const eKey = `${current},${e.to}`;
      if ((edgeUsed.get(eKey) || 0) > 0) continue;

      // Signed angle from reference to edge direction, in (-π, π].
      let angle = Math.atan2(
        refDx * e.dy - refDy * e.dx,
        refDx * e.dx + refDy * e.dy,
      );
      if (angle <= -Math.PI) angle += 2 * Math.PI;

      // turnSign=+1 → maximise angle (leftmost / most CCW)
      // turnSign=-1 → minimise angle (rightmost / most CW), achieved by
      //               maximising -angle.
      const score = angle * turnSign;

      if (score > bestScore) {
        bestScore = score;
        bestIdx = k;
      }
    }

    if (bestIdx < 0) break;

    const chosen = adj[bestIdx];
    const eKey = `${current},${chosen.to}`;
    edgeUsed.set(eKey, (edgeUsed.get(eKey) || 0) + 1);

    inDx = chosen.dx;
    inDy = chosen.dy;
    current = chosen.to;

    if (current === startNode) break;
  }

  return contour.length >= 3 ? contour : splitLoop.map((p) => ({x: p.x, y: p.y}));
}

/**
 * Extract the outermost simple contour from a split polygon.
 *
 * We determine the input's winding direction, then walk with the
 * matching turn preference:
 *   - CCW (positive area) → leftmost turns  (turnSign = +1)
 *   - CW  (negative area) → rightmost turns (turnSign = -1)
 *
 * Both produce the outer boundary in the same winding as the input.
 */
function extractOutermostContour(splitLoop) {
  // Determine winding from the original split-loop order.
  const area = signedLoopArea(splitLoop);
  const turnSign = area >= 0 ? 1 : -1;
  return walkContour(splitLoop, turnSign);
}

// ─── Public API ─────────────────────────────────────────────────────────

/**
 * Remove self-intersections from a closed polygon by detecting crossings,
 * splitting edges, and extracting only the outermost simple contour.
 *
 * If the polygon has no self-intersections, it is returned unchanged
 * (with a fresh copy of each point).
 *
 * @param {Array<{x:number, y:number}>} loop — closed polygon vertices
 * @returns {Array<{x:number, y:number}>} — simple (non-self-intersecting) polygon
 */
export function cleanOffsetLoop(loop) {
  if (!Array.isArray(loop) || loop.length < 3) {
    return Array.isArray(loop) ? loop.map((p) => ({x: p.x, y: p.y})) : [];
  }

  const intersections = findSelfIntersections(loop);

  // Fast path: no crossings — just clone.
  if (!intersections.length) {
    return loop.map((p) => ({x: p.x, y: p.y}));
  }

  // Split, extract, return.
  const splitLoop = splitEdgesAtIntersections(loop, intersections);
  const contour = extractOutermostContour(splitLoop);

  // Sanity: the outer contour must have the same winding as the input.
  // If the winding flipped (shouldn't happen, but be safe), flip it back.
  const inputArea = signedLoopArea(loop);
  const outputArea = signedLoopArea(contour);
  if ((inputArea > 0) !== (outputArea > 0)) {
    contour.reverse();
  }

  return contour;
}

/**
 * Quick boolean check: does a closed polygon have any self-intersections?
 */
export function hasSelfIntersections(loop) {
  if (!Array.isArray(loop) || loop.length < 4) return false;
  return findSelfIntersections(loop).length > 0;
}

